name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore src/TechAds.sln
      - name: Build
        run: dotnet build src/TechAds.sln --no-restore
      - name: Test
        run: dotnet test src/TechAds.sln --no-build --verbosity normal
